apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: platform-as-code.crd-binding
  labels:
    app: crd-hook
webhooks:
  - name: platform-as-code.crd-binding.v1
    namespaceSelector:
      matchExpressions:
      - key: "managedby"
        operator: "In"
        values: ["kubeplus"]
    clientConfig:
      service:
        name: crd-hook-service
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE","DELETE"]
        apiGroups: ["workflows.kubeplus", "apps", "extensions", "", "apiextensions.k8s.io", "platformapi.kubeplus"]
        apiVersions: ["v1alpha1", "v1", "v1beta1"]
        resources: ["resourcepolicies", "resourcecompositions", "resourcemonitors", "resourceevents", "pods", "customresourcedefinitions","namespaces","*"]
        #resources: ["resourcepolicies", "deployments", "statefulsets", "replicasets", "daemonsets", "replicationcontrollers", "pods", "customresourcedefinitions","namespaces"]
