apiVersion: platformstack.kubeplus/v1
kind: PlatformStack
metadata:
  name: moodle1-stack-with-backups
spec:
  labelSelector: moodle1-stack-with-backups
  stackElements: 
    - kind: Secret
      name: cluster1-secret
    - kind: Secret
      name: backups-aws-secret
    - kind: MysqlCluster
      name: cluster1
      dependsOn:
        - name: cluster1-secret
        - name: backups-aws-secret
    - kind: Moodle
      name: moodle1
      dependsOn:
        - name: cluster1
        - name: cluster1-secret
    - kind: Secret
      name: s3-secret
    - kind: Restic
      name: moodle-restic
      dependsOn:
        - name: s3-secret
        - name: moodle1
