apiVersion: workflows.kubeplus/v1alpha1
kind: PlatformWorkflow
metadata:
  name: moodle1-stack-with-backups
spec:
  stackElements: 
    - kind: MysqlCluster
      name: cluster1
    - kind: Moodle
      name: moodle1
      dependsOn:
        - name: cluster1
      policy:
        addlabel:
          - label: ImportValue(Restic:default.moodle-restic.selector.matchLabels)
            onsubresource: Deployment[.<name>], Secret[.<name>]
    - kind: Restic
      name: moodle-restic
      dependsOn:
        - name: moodle1
        
