apiVersion: workflows.kubeplus/v1alpha1
kind: PlatformWorkflow
metadata:
  name: mysqlcluster-workflow
spec:
  stackElements:
    - kind: Secret
      name: cluster1-secret
      namespace: default
    - kind: MysqlCluster
      name: cluster1
      namespace: namespace1
      dependsOn:
       - name: cluster1-secret
    - kind: Moodle
      name: moodle1
      dependsOn:
        - name: cluster1
        - name: cluster1-secret
  customAPI:
    - kind: MysqlClusterStack
      group: platformapi.kubeplus
      version: v1alpha1
      plural: mysqlclusterstacks
      chartURL: https://github.com/cloud-ark/operatorcharts/blob/master/mysqlcluster-0.1.0.tgz?raw=true
      chartName: mysqlcluster

