apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcecompositions.workflows.kubeplus
spec:
  group: workflows.kubeplus
  version: v1alpha1
  names:
    kind: ResourceComposition 
    plural: resourcecompositions 
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcepolicies.workflows.kubeplus
spec:
  group: workflows.kubeplus
  version: v1alpha1
  names:
    kind: ResourcePolicy 
    plural: resourcepolicies 
  scope: Namespaced
---
apiVersion: v1
kind: Pod
metadata:
  name: kubeplus-operator
  labels:
    app: kubeplus-operator
spec:
  containers:
  - name: platform-operator
    #image: lmecld/platform-operator:0.0.4-alpha2
    image: gcr.io/disco-horizon-103614/platform-operator:0.0.6
    imagePullPolicy: Always
    command: [ "/platform-operator"]
#  - name: helmer
#    image: gcr.io/disco-horizon-103614/helm-pod:latest
#    imagePullPolicy: Always
#    command: ["/root/helm-pod"]
#    volumeMounts:
#    - mountPath: /chart
#      name: chart-volume
#  volumes:
#    - name: chart-volume
#      emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: kubeplus-operator
spec:
  selector:
    app: kubeplus-operator
  ports:
  - protocol: TCP
    port: 91
    targetPort: 8090
---
